<?php

declare(strict_types=1);

namespace Rugaard\DMI\Enums\Meteorological;

use function serialize;

/**
 * Enum WeatherCondition.
 *
 * @return int
 */
enum WeatherCondition: int
{
    /**
     * 0-99 = From manual observation stations
     */
    case ManualClear = 0;
    case ManualCloudsDissolvingPastHour = 1;
    case ManualSkyUnchangedPastHour = 2;
    case ManualCloudsDevelopingPastHour = 3;
    case ManualVisibilityReducedBySmokeOrAshes = 4;
    case ManualHaze = 5;
    case ManualWidespreadDustSuspension = 6;
    case ManualDustSandNoWhirlsStorm = 7;
    case ManualDustSandWhirlsDevelopedNoStorm = 8;
    case ManualDustSandStormsInSight = 9;
    case ManualMist = 10;
    case ManualFogOrIceFogPatches = 11;
    case ManualFogOrIceFogContinuous = 12;
    case ManualLightningVisibleNoThunder = 13;
    case ManualPrecipitationInSightNoTouchdown = 14;
    case ManualPrecipitationInSightDistantTouchdown = 15;
    case ManualPrecipitationInSightNearbyTouchdown = 16;
    case ManualThunderstorm = 17;
    case ManualSquallsOrWithinSight = 18;
    case ManualFunnelCloudsOrWithinSight = 19;
    case ManualDrizzleOrSnowGrainsPastHour = 20;
    case ManualRainPastHour = 21;
    case ManualSnowPastHour = 22;
    case ManualRainSnowOrIcePalletsPastHour = 23;
    case ManualFreezingDrizzleOrFreezingRainPastHour = 24;
    case ManualRainShowersPastHour = 25;
    case ManualSnowOrRainAndSnowShowersPastHour = 26;
    case ManualHailOrRainAndHailShowersPastHour = 27;
    case ManualFogOrIceFogPastHour = 28;
    case ManualThunderstormPastHour = 29;
    case ManualSlightModerateDustSandStormDecreasedPastHour = 30;
    case ManualSlightModerateDustSandStormUnchangedPastHour = 31;
    case ManualSlightModerateDustSandStormIncreasedPastHour = 32;
    case ManualSevereDustSandStormDecreasedPastHour = 33;
    case ManualSevereDustSandStormUnchangedPastHour = 34;
    case ManualSevereDustSandStormIncreasedPastHour = 35;
    case ManualSlightModerateBlowingSnowLow = 36;
    case ManualHeavyDriftingSnowLow = 37;
    case ManualSlightModerateBlowingSnowHigh = 38;
    case ManualHeavyDriftingSnowHigh = 39;
    case ManualFogOrIceFogInDistancePastHour = 40;
    case ManualFogOrIceFogInPatches = 41;
    case ManualFogOrIceFogBecomingThinnerSkyVisiblePastHour = 42;
    case ManualFogOrIceFogBecomingThinnerSkyInvisiblePastHour = 43;
    case ManualFogOrIceFogUnchangedSkyVisiblePastHour = 44;
    case ManualFogOrIceFogUnchangedSkyInvisiblePastHour = 45;
    case ManualFogOrIceFogBecomingThickerSkyVisiblePastHour = 46;
    case ManualFogOrIceFogBecomingThickerSkyInvisiblePastHour = 47;
    case ManualFogDepositingRimeSkyVisible = 48;
    case ManualFogDepositingRimeSkyInvisible = 49;
    case ManualSlightDrizzleIntermittent = 50;
    case ManualSlightDrizzleContinuous = 51;
    case ManualModerateDrizzleIntermittent = 52;
    case ManualModerateDrizzleContinuous = 53;
    case ManualHeavyDrizzleIntermittent = 54;
    case ManualHeavyDrizzleContinuous = 55;
    case ManualSlightDrizzleFreezing = 56;
    case ManualModerateHeavyDrizzleFreezing = 57;
    case ManualSlightDrizzleRain = 58;
    case ManualModerateHeavyDrizzleRain = 59;
    case ManualSlightRainIntermittent = 60;
    case ManualSlightRainContinuous = 61;
    case ManualModerateRainIntermittent = 62;
    case ManualModerateRainContinuous = 63;
    case ManualHeavyRainIntermittent = 64;
    case ManualHeavyRainContinuous = 65;
    case ManualSlightRainFreezing = 66;
    case ManualModerateHeavyRainFreezing = 67;
    case ManualSlightRainDrizzleAndSnow = 68;
    case ManualModerateHeavyRainDrizzleAndSnow = 69;
    case ManualSlightFallingSnowflakesIntermittent = 70;
    case ManualSlightFallingSnowflakesContinuous = 71;
    case ManualModerateFallingSnowflakesIntermittent = 72;
    case ManualModerateFallingSnowflakesContinuous = 73;
    case ManualHeavyFallingSnowflakesIntermittent = 74;
    case ManualHeavyFallingSnowflakesContinuous = 75;
    case ManualDiamondDust = 76;
    case ManualSnowGrains = 77;
    case ManualIsolatedStarLikeSnowCrystals = 78;
    case ManualIcePellets = 79;
    case ManualSlightRainShowers = 80;
    case ManualModerateHeavyRainShowers = 81;
    case ManualViolentRainShowers = 82;
    case ManualSlightRainSnowShowersMixed = 83;
    case ManualModerateHeavyRainSnowShowersMixed = 84;
    case ManualSlightSnowShowers = 85;
    case ManualModerateHeavySnowShowers = 86;
    case ManualSlightSnowPelletsOrSmallHailShowers = 87;
    case ManualModerateHeavySnowPelletsOrSmallHailShowers = 88;
    case ManualSlightHailShowers = 89;
    case ManualModerateHeavyHailShowers = 90;
    case ManualSlightRainPrecedingThunderstorm = 91;
    case ManualModerateHeavyRainPrecedingThunderstorm = 92;
    case ManualSlightSnowOrHailOrRainAndSnowMixedPrecedingThunderstorm = 93;
    case ManualModerateHeavySnowOrHailOrRainAndSnowMixedPrecedingThunderstorm = 94;
    case ManualSlightModerateThunderstormWithRainOrRainSnowMixed = 95;
    case ManualSlightModerateThunderstormWithHail = 96;
    case ManualHeavyThunderstormWithRainOrRainSnowMixed = 97;
    case ManualThunderstormWithDustSandStorm = 98;
    case ManualHeavyThunderstormWithHail = 99;

    /**
     * 100-199 = From automatic weather stations.
     */
    case Clear = 100;
    case CloudsDissolvingPastHour = 101;
    case SkyUnchangedPastHour = 102;
    case CloudsDevelopingPastHour = 103;
    case HazeSmokeDustSuspensionInAirVisibilityOver1Km = 104;
    case HazeSmokeDustSuspensionInAirVisibilityUnder1Km = 105;
    case Mist = 110;
    case DiamondDust = 111;
    case DistantLightning = 112;
    case Squalls = 118;
    case FogOrIceFogPastHour = 120;
    case PrecipitationPastHour = 121;
    case DrizzleOrSnowGrainsPastHour = 122;
    case RainPastHour = 123;
    case SnowPastHour = 124;
    case FreezingDrizzleOrFreezingRainPastHour = 125;
    case ThunderstormPastHour = 126;
    case BlowingDriftingSnowOrSand = 127;
    case BlowingDriftingSnowOrSandVisibilityOver1Km = 128;
    case BlowingDriftingSnowOrSandVisibilityUnder1Km = 129;
    case Fog = 130;
    case FogOrIceFogPatches = 131;
    case FogOrIceFogThinnerPastHour = 132;
    case FogOrIceFogUnchangedPastHour = 133;
    case FogOrIceFogThickerPastHour = 134;
    case FogDepositingRime = 135;
    case Precipitation = 140;
    case SlightModeratePrecipitation = 141;
    case HeavyPrecipitation = 142;
    case SlightModerateLiquidPrecipitation = 143;
    case HeavyLiquidPrecipitation = 144;
    case SlightModerateSolidPrecipitation = 145;
    case HeavySolidPrecipitation = 146;
    case SlightModerateFreezingPrecipitation = 147;
    case HeavyFreezingPrecipitation = 148;
    case Drizzle = 150;
    case SlightDrizzle = 151;
    case ModerateDrizzle = 152;
    case HeavyDrizzle = 153;
    case SlightDrizzleFreezing = 154;
    case ModerateDrizzleFreezing = 155;
    case HeavyDrizzleFreezing = 156;
    case SlightDrizzleRain = 157;
    case ModerateHeavyDrizzleRain = 158;
    case Rain = 160;
    case SlightRain = 161;
    case ModerateRain = 162;
    case HeavyRain = 163;
    case SlightRainFreezing = 164;
    case ModerateRainFreezing = 165;
    case HeavyRainFreezing = 166;
    case SlightRainSnow = 167;
    case ModerateHeavyRainSnow = 168;
    case Snow = 170;
    case SlightSnow = 171;
    case ModerateSnow = 172;
    case HeavySnow = 173;
    case SlightIcePellets = 174;
    case ModerateIcePellets = 175;
    case HeavyIcePellets = 176;
    case SnowGrains = 177;
    case IceCrystals = 178;
    case ShowersOrIntermittentPrecipitation = 180;
    case SlightRainShowersOrIntermittentRain = 181;
    case ModerateRainShowersOrIntermittentRain = 182;
    case HeavyRainShowersOrIntermittentRain = 183;
    case ViolentRainShowersOrIntermittentRain = 184;
    case SlightSnowShowersOrIntermittentSnow = 185;
    case ModerateSnowShowersOrIntermittentSnow = 186;
    case HeavySnowShowersOrIntermittentSnow = 187;
    case Hail = 189;
    case Thunderstorm = 190;
    case SlightModerateThunderstorm = 191;
    case SlightModerateThunderstormShowers = 192;
    case SlightModerateThunderstormHail = 193;
    case HeavyThunderstorm = 194;
    case HeavyThunderstormShowers = 195;
    case HeavyThunderstormHail = 196;
    case Tornado = 199;

    /**
     * Get description of weather condition.
     *
     * @return string
     */
    public function description(): string
    {
        return match ($this) {
            self::ManualClear => 'Clear, cloud development not observed or not observable during the past hour',
            self::ManualCloudsDissolvingPastHour => 'Clouds generally dissolving or becoming less developed during the past hour',
            self::ManualSkyUnchangedPastHour => 'State of sky on the whole unchanged during the past hour',
            self::ManualCloudsDevelopingPastHour => 'Clouds generally forming or developing during the past hour',
            self::ManualVisibilityReducedBySmokeOrAshes => 'Visibility reduced by smoke, e.g. veldt or forest fires, industrial smoke or volcanic ashes',
            self::ManualHaze => 'Haze',
            self::ManualWidespreadDustSuspension => 'Widespread dust in suspension in the air, not raised by wind at or near the station at the time of observation',
            self::ManualDustSandNoWhirlsStorm => 'Dust or sand raised by wind at or near the station at the time of observation, but no well developed dust whirl(s) or sand whirl(s), and no duststorm or sandstorm seen',
            self::ManualDustSandWhirlsDevelopedNoStorm => 'Well developed dust whirl(s) or sand whirl(s) seen at or near the station during the preceding hour or at the time ot observation, but no duststorm or sandstorm',
            self::ManualDustSandStormsInSight => 'Duststorm or sandstorm within sight at the time of observation, or at the station during the preceding hour',
            self::ManualMist => 'Mist',
            self::ManualFogOrIceFogPatches => 'Shallow fog or ice fog patches at the station, whether on land or sea, not deeper than about 2 metres on land or 10 metres at sea',
            self::ManualFogOrIceFogContinuous => 'More or less continuous fog or ice fog at the station, whether on land or sea, not deeper than about 2 metres on land or 10 metres at sea',
            self::ManualLightningVisibleNoThunder => 'Lightning visible, no thunder heard',
            self::ManualPrecipitationInSightNoTouchdown => 'Precipitation within sight, not reaching the ground or the surface of the sea',
            self::ManualPrecipitationInSightDistantTouchdown => 'Precipitation within sight, reaching the ground or the surface of the sea, but distant, i.e. estimated to be more than 5 km from the station',
            self::ManualPrecipitationInSightNearbyTouchdown => 'Precipitation within sight, reaching the ground or the surface of the sea, near to, but not at the station',
            self::ManualThunderstorm => 'Thunderstorm, but no precipitation at the time of observation',
            self::ManualSquallsOrWithinSight => 'Squalls at or within sight of the station during the preceding hour or at the time of observation',
            self::ManualFunnelCloudsOrWithinSight => 'Funnel cloud(s) (tornado cloud or water-spout) at or within sight of the station during the preceding hour or at the time of observation',
            self::ManualDrizzleOrSnowGrainsPastHour => 'Drizzle (not freezing) or snow grains not falling as shower(s) at the station during the preceding hour but not at the time of observation',
            self::ManualRainPastHour => 'Rain (not freezing), not falling as shower(s), at the station during the preceding hour but not at the time of observation',
            self::ManualSnowPastHour => 'Snow (not freezing), not falling as shower(s), at the station during the preceding hour but not at the time of observation',
            self::ManualRainSnowOrIcePalletsPastHour => 'Rain and snow or ice pellets, not falling as shower(s), at the station during the preceding hour but not at the time of observation',
            self::ManualFreezingDrizzleOrFreezingRainPastHour => 'Freezing drizzle or freezing rain, not falling as shower(s), at the station during the preceding hour but not at the time of observation',
            self::ManualRainShowersPastHour => 'Shower(s) of rain, at the station during the preceding hour but not at the time of observation',
            self::ManualSnowOrRainAndSnowShowersPastHour => 'Shower(s) of snow, or of rain and snow, at the station during the preceding hour but not at the time of observation',
            self::ManualHailOrRainAndHailShowersPastHour => 'Shower(s) of hail, or of rain and hail, at the station during the preceding hour but not at the time of observation',
            self::ManualFogOrIceFogPastHour => 'Fog or ice fog, at the station during the preceding hour but not at the time of observation',
            self::ManualThunderstormPastHour => 'Thunderstorm (with or without precipitation), at the station during the preceding hour but not at the time of observation',
            self::ManualSlightModerateDustSandStormDecreasedPastHour => 'Slight or moderate, duststorm or sandstorm, has decreased during the preceding hour',
            self::ManualSlightModerateDustSandStormUnchangedPastHour => 'Slight or moderate, duststorm or sandstorm, has no appreciable change during the preceding hour',
            self::ManualSlightModerateDustSandStormIncreasedPastHour => 'Slight or moderate, duststorm or sandstorm, has begun or has increased during the preceding hour',
            self::ManualSevereDustSandStormDecreasedPastHour => 'Severe duststorm or sandstorm, has decreased during the preceding hour',
            self::ManualSevereDustSandStormUnchangedPastHour => 'Severe duststorm or sandstorm, has no appreciable change during the preceding hour',
            self::ManualSevereDustSandStormIncreasedPastHour => 'Severe duststorm or sandstorm, has begun or has increased during the preceding hour',
            self::ManualSlightModerateBlowingSnowLow => 'Slight or moderate blowing snow (generally low, below eye level)',
            self::ManualHeavyDriftingSnowLow => 'Heavy drifting snow (generally low, below eye level)',
            self::ManualSlightModerateBlowingSnowHigh => 'Slight or moderate blowing snow (generally high, above eye level)',
            self::ManualHeavyDriftingSnowHigh => 'Heavy drifting snow (generally high, above eye level)',
            self::ManualFogOrIceFogInDistancePastHour => 'Fog or ice fog, at a distance at the time of observation, but not at the station during the preceding hour, the fog or ice fog extending to a level above that of the observer',
            self::ManualFogOrIceFogInPatches => 'Fog or ice fog in patches',
            self::ManualFogOrIceFogBecomingThinnerSkyVisiblePastHour => 'Fog or ice fog, has become thinner during the preceding hour, sky visible',
            self::ManualFogOrIceFogBecomingThinnerSkyInvisiblePastHour => 'Fog or ice fog, has become thinner during the preceding hour, sky invisible',
            self::ManualFogOrIceFogUnchangedSkyVisiblePastHour => 'Fog or ice fog, has no appreciable change during the preceding hour, sky visible',
            self::ManualFogOrIceFogUnchangedSkyInvisiblePastHour => 'Fog or ice fog, has no appreciable change during the preceding hour, sky invisible',
            self::ManualFogOrIceFogBecomingThickerSkyVisiblePastHour => 'Fog or ice fog, has begun or has become thicker during the preceding hour, sky visible',
            self::ManualFogOrIceFogBecomingThickerSkyInvisiblePastHour => 'Fog or ice fog, has begun or has become thicker during the preceding hour, sky invisible',
            self::ManualFogDepositingRimeSkyVisible => 'Fog, depositing rime, sky visible',
            self::ManualFogDepositingRimeSkyInvisible => 'Fog, depositing rime, sky invisible',
            self::ManualSlightDrizzleIntermittent => 'Drizzle, not freezing, intermittent, slight at time of observation',
            self::ManualSlightDrizzleContinuous => 'Drizzle, not freezing, continuous, slight at time of observation',
            self::ManualModerateDrizzleIntermittent => 'Drizzle, not freezing, intermittent, moderate at time of observation',
            self::ManualModerateDrizzleContinuous => 'Drizzle, not freezing, continuous, moderate at time of observation',
            self::ManualHeavyDrizzleIntermittent => 'Drizzle, not freezing, intermittent, heavy (dense) at time of observation',
            self::ManualHeavyDrizzleContinuous => 'Drizzle, not freezing, continuous, heavy (dense) at time of observation',
            self::ManualSlightDrizzleFreezing => 'Drizzle, freezing, slight',
            self::ManualModerateHeavyDrizzleFreezing => 'Drizzle, freezing, Moderate or heavy (dense)',
            self::ManualSlightDrizzleRain => 'Drizzle and rain, slight',
            self::ManualModerateHeavyDrizzleRain => 'Drizzle and rain, moderate or heavy (dense)',
            self::ManualSlightRainIntermittent => 'Rain, not freezing, intermittent, slight at time of observation',
            self::ManualSlightRainContinuous => 'Rain, not freezing, continuous, slight at time of observation',
            self::ManualModerateRainIntermittent => 'Rain, not freezing, intermittent, moderate at time of observation',
            self::ManualModerateRainContinuous => 'Rain, not freezing, continuous, moderate at time of observation',
            self::ManualHeavyRainIntermittent => 'Rain, not freezing, intermittent, heavy (dense) at time of observation',
            self::ManualHeavyRainContinuous => 'Rain, not freezing, continuous, heavy (dense) at time of observation',
            self::ManualSlightRainFreezing => 'Rain, freezing, slight',
            self::ManualModerateHeavyRainFreezing => 'Rain, freezing, moderate or heavy (dense)',
            self::ManualSlightRainDrizzleAndSnow => 'Rain or drizzle and snow, slight',
            self::ManualModerateHeavyRainDrizzleAndSnow => 'Rain or drizzle and snow, moderte or heavy (dense)',
            self::ManualSlightFallingSnowflakesIntermittent => 'Fall of snowflakes, intermittent, slight at time of observation',
            self::ManualSlightFallingSnowflakesContinuous => 'Fall of snowflakes, continuous, slight at time of observation',
            self::ManualModerateFallingSnowflakesIntermittent => 'Fall of snowflakes, intermittent, moderate at time of observation',
            self::ManualModerateFallingSnowflakesContinuous=> 'Fall of snowflakes, continuous, moderate at time of observation',
            self::ManualHeavyFallingSnowflakesIntermittent => 'Fall of snowflakes, intermittent, heavy (dense) at time of observation',
            self::ManualHeavyFallingSnowflakesContinuous => 'Fall of snowflakes, continuous, heavy (dense) at time of observation',
            self::ManualDiamondDust => 'Diamond dust (with or without fog)',
            self::ManualSnowGrains => 'Snow grains (with or without fog)',
            self::ManualIsolatedStarLikeSnowCrystals => 'Isolated star-like snow crystals (with or without fog)',
            self::ManualIcePellets => 'Ice pellets',
            self::ManualSlightRainShowers => 'Rain shower(s), slight',
            self::ManualModerateHeavyRainShowers => 'Rain shower(s), moderate or heavy (dense)',
            self::ManualViolentRainShowers => 'Rain shower(s), violent',
            self::ManualSlightRainSnowShowersMixed => 'Shower(s) of rain and snow mixed, slight',
            self::ManualModerateHeavyRainSnowShowersMixed => 'Shower(s) of rain and snow mixed, moderate or heavy',
            self::ManualSlightSnowShowers => 'Snow shower(s), slight',
            self::ManualModerateHeavySnowShowers => 'Snow shower(s), moderate or heavy (dense)',
            self::ManualSlightSnowPelletsOrSmallHailShowers => 'Shower(s) of snow pellets or small hail, slight, with or without rain or rain and snow mixed',
            self::ManualModerateHeavySnowPelletsOrSmallHailShowers => 'Shower(s) of snow pellets or small hail, moderate or heavy (dense), with or without rain or rain and snow mixed',
            self::ManualSlightHailShowers => 'Shower(s) of hail, slight, with or without rain or rain and snow mixed, not associated with thunder',
            self::ManualModerateHeavyHailShowers => 'Shower(s) of hail, moderate or heavy (dense), with or without rain or rain and snow mixed, not associated with thunder',
            self::ManualSlightRainPrecedingThunderstorm => 'Rain, slight, at time of observation, thunderstorm during preceding hour, but not at time of observation',
            self::ManualModerateHeavyRainPrecedingThunderstorm => 'Rain, moderate or heavy (dense), at time of observation, thunderstorm during preceding hour, but not at time of observation',
            self::ManualSlightSnowOrHailOrRainAndSnowMixedPrecedingThunderstorm => 'Snow, slight, or rain and snow mixed, or hail, at time of observation, thunderstorm during preceding hour, but not at time of observation',
            self::ManualModerateHeavySnowOrHailOrRainAndSnowMixedPrecedingThunderstorm => 'Snow, moderate or heavy (dense), or rain and snow mixed, or hail, at time of observation, thunderstorm during preceding hour, but not at time of observation',
            self::ManualSlightModerateThunderstormWithRainOrRainSnowMixed => 'Thunderstorm, slight or moderate, without hail, but with rain and/or snow, at time of observation',
            self::ManualSlightModerateThunderstormWithHail => 'Thunderstorm, slight or moderate, with hail, at time of observation',
            self::ManualHeavyThunderstormWithRainOrRainSnowMixed => 'Thunderstorm, heavy, without hail, but with rain and/or snow, at time of observation',
            self::ManualThunderstormWithDustSandStorm => 'Thunderstorm combined with duststorm or sandstorm, at time of observation',
            self::ManualHeavyThunderstormWithHail => 'Thunderstorm, heavy, with hail, at time of observation',
            self::Clear => 'Clear, no significant weather observed',
            self::CloudsDissolvingPastHour => 'Clouds generally dissolving or becoming less developed during the past hour',
            self::SkyUnchangedPastHour => 'State of sky on the whole unchanged during the past hour',
            self::CloudsDevelopingPastHour => 'Clouds generally forming or developing during the past hour',
            self::HazeSmokeDustSuspensionInAirVisibilityOver1Km => 'Haze, smoke or dust suspension in the air, visibility equal to or greater than 1 kilometer',
            self::HazeSmokeDustSuspensionInAirVisibilityUnder1Km => 'Haze, smoke or dust suspension in the air, visibility less than 1 kilometer',
            self::Mist => 'Mist',
            self::DiamondDust => 'Diamond dust',
            self::DistantLightning => 'Distant lightning',
            self::Squalls => 'Squalls',
            self::FogOrIceFogPastHour => 'Fog or ice fog, at the station during the preceding hour, but not at the time of observation',
            self::PrecipitationPastHour => 'Precipitation, at the station during the preceding hour, but not at the time of observation',
            self::DrizzleOrSnowGrainsPastHour => 'Drizzle or snow grains, at the station during the preceding hour, but not at the time of observation',
            self::RainPastHour => 'Rain, at the station during the preceding hour, but not at the time of observation',
            self::SnowPastHour => 'Snow, at the station during the preceding hour, but not at the time of observation',
            self::FreezingDrizzleOrFreezingRainPastHour => 'Freezing drizzle or freezing rain, at the station during the preceding hour, but not at the time of observation',
            self::ThunderstormPastHour => 'Thunderstorm (with or without precipitation), at the station during the preceding hour, but not at the time of observation',
            self::BlowingDriftingSnowOrSand => 'Blowing or drifting snow or sand',
            self::BlowingDriftingSnowOrSandVisibilityOver1Km => 'Blowing or drifting snow or sand, visibility equal to or greater than 1 kilometer',
            self::BlowingDriftingSnowOrSandVisibilityUnder1Km => 'Blowing or drifting snow or sand, visibility less than 1 kilometer',
            self::Fog => 'Fog',
            self::FogOrIceFogPatches => 'Fog or ice fog in patches',
            self::FogOrIceFogThinnerPastHour => 'Fog or ice fog, has become thinner during the past hour',
            self::FogOrIceFogUnchangedPastHour => 'Fog or ice fog, no appreciable change during the past hour',
            self::FogOrIceFogThickerPastHour => 'Fog or ice fog, has begun or become thicker during the past hour',
            self::FogDepositingRime => 'Fog, depositing rime',
            self::Precipitation => 'Precipitation',
            self::SlightModeratePrecipitation => 'Precipitation, slight or moderate',
            self::HeavyPrecipitation => 'Precipitation, heavy',
            self::SlightModerateLiquidPrecipitation => 'Liquid precipitation, slight or moderate',
            self::HeavyLiquidPrecipitation => 'Liquid precipitation, heavy',
            self::SlightModerateSolidPrecipitation => 'Solid precipitation, slight or moderate',
            self::HeavySolidPrecipitation => 'Solid precipitation, heavy',
            self::SlightModerateFreezingPrecipitation => 'Freezing precipitation, slight or moderate',
            self::HeavyFreezingPrecipitation => 'Freezing precipitation, heavy',
            self::Drizzle => 'Drizzle',
            self::SlightDrizzle => 'Drizzle, not freezing, slight',
            self::ModerateDrizzle => 'Drizzle, not freezing, moderate',
            self::HeavyDrizzle => 'Drizzle, not freezing, heavy',
            self::SlightDrizzleFreezing => 'Drizzle, freezing, slight',
            self::ModerateDrizzleFreezing => 'Drizzle, freezing, moderate',
            self::HeavyDrizzleFreezing => 'Drizzle, freezing, heavy',
            self::SlightDrizzleRain => 'Drizzle and rain, slight',
            self::ModerateHeavyDrizzleRain => 'Drizzle and rain, moderate or heavy',
            self::Rain => 'Rain',
            self::SlightRain => 'Rain, not freezing, slight',
            self::ModerateRain => 'Rain, not freezing, moderate',
            self::HeavyRain => 'Rain, not freezing, heavy',
            self::SlightRainFreezing => 'Rain, freezing, slight',
            self::ModerateRainFreezing => 'Rain, freezing, moderate',
            self::HeavyRainFreezing => 'Rain, freezing, heavy',
            self::SlightRainSnow => 'Rain (or drizzle) and snow, slight',
            self::ModerateHeavyRainSnow => 'Rain (or drizzle) and snow, moderate or heavy',
            self::Snow => 'Snow',
            self::SlightSnow => 'Snow, slight',
            self::ModerateSnow => 'Snow, moderate',
            self::HeavySnow => 'Snow, heavy',
            self::SlightIcePellets => 'Ice pellets, slight',
            self::ModerateIcePellets => 'Ice pellets, moderate',
            self::HeavyIcePellets => 'Ice pellets, heavy',
            self::SnowGrains => 'Snow grains',
            self::IceCrystals => 'Ice crystals',
            self::ShowersOrIntermittentPrecipitation => 'Shower(s) or intermittent precipitation',
            self::SlightRainShowersOrIntermittentRain => 'Rain shower(s) or intermittent precipitation, slight',
            self::ModerateRainShowersOrIntermittentRain => 'Rain shower(s) or intermittent precipitation, moderate',
            self::HeavyRainShowersOrIntermittentRain => 'Rain shower(s) or intermittent precipitation, heavy',
            self::ViolentRainShowersOrIntermittentRain => 'Rain shower(s) or intermittent precipitation, violet',
            self::SlightSnowShowersOrIntermittentSnow => 'Snow shower(s) or intermittent snow, slight',
            self::ModerateSnowShowersOrIntermittentSnow => 'Snow shower(s) or intermittent snow, moderate',
            self::HeavySnowShowersOrIntermittentSnow => 'Snow shower(s) or intermittent snow, heavy',
            self::Hail => 'Hail',
            self::Thunderstorm => 'Thunderstorm',
            self::SlightModerateThunderstorm => 'Thunderstorm, slight or moderate, with no precipitation',
            self::SlightModerateThunderstormShowers => 'Thunderstorm, slight or moderate, with rain showers and/or snow showers',
            self::SlightModerateThunderstormHail => 'Thunderstorm, slight or moderate, with hail',
            self::HeavyThunderstorm => 'Thunderstorm, heavy, with no precipitation',
            self::HeavyThunderstormShowers => 'Thunderstorm, heavy, with rain showers and/or snow showers',
            self::HeavyThunderstormHail => 'Thunderstorm, heavy, with hail',
            self::Tornado => 'Tornado',
        };
    }
}
